/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 7784698fd2a117639d1597465ce5fcf5)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "MySimpleDurableObject" | "MyExtendedDurableObject";
	}
	interface Env {
		MY_SIMPLE_DURABLE_OBJECT: DurableObjectNamespace<import("./src/index").MySimpleDurableObject>;
		MY_EXTENDED_DURABLE_OBJECT: DurableObjectNamespace<import("./src/index").MyExtendedDurableObject>;
		MY_SIMPLE_ENTRYPOINT: Service<typeof import("./src/index").SimpleWorkerEntrypoint>;
		MY_EXTENDED_ENTRYPOINT: Service<typeof import("./src/index").ExtendedWorkerEntrypoint>;
	}
}
interface Env extends Cloudflare.Env {}
